dehixorg/dehix_alpha_frontend

src/app/page.tsx
src/components/navbar.tsx
src/components/shared/iconCard.tsx

Description: 
1) changed the font styling of the main heading, sub-heading, and navbar headings
2) applied a deepened background color
3) applied shadow and transform effect on card icons on hovering

landing page styling changes

---

src/app/auth/login/page.tsx
src/app/home/footer/page.tsx
src/app/page.tsx
src/dashboard/card/page.tsx
src/lib/utils.ts

add footer ro the landing page and reusabe card component using props

Abhi ladingpage and card

---

package-lock.json
package.json
src/app/profile/page.tsx
src/components/ProfileSidebar.tsx
src/components/ui/scroll-area.tsx

Description:
1) implemented profile sidebar component for profile page
2) implemented main profile page

implemented profile page

---

package-lock.json
package.json
src/app/dash/oracle/page.tsx
src/app/dash/page.tsx
src/app/dash/personalinfo/page.tsx
src/app/home/portfolio/page.tsx
src/app/page.tsx
src/components/SVGIcon.tsx
src/components/ui/form.tsx
src/components/ui/select.tsx
src/config/firebaseConfig.tsx
src/dashboard/card/page.tsx
tsconfig.json

add styling to card
make portfolio reusabe

reusable cards and portfolio

---

src/app/comp-test/page.tsx
src/components/newcomp-test/act-proj/active-card.tsx
src/components/newcomp-test/pen-proj/pending-card.tsx

path
inside src->app->comp-test->page.tsx (main code )
inside src->components->newcomp-test->_act-proj_ (reusable component ) **{active project, total revenue, oracle work cards  are made using this}**
inside src->components->newcomp-test->_pen-proj_(reusable component ) **{ pending project card is made using this component}**

cards components

---

src/app/comp-test/page.tsx
src/app/dashboard/page.tsx
src/components/newcomp-test/act-proj/active-card.tsx
src/components/newcomp-test/pen-proj/pending-card.tsx

Reverts dehixorg/dehix_alpha_frontend#17

Revert "dashboard component"

---

src/app/oppor/page.tsx
src/components/opportunities/company-size/company.tsx
src/components/opportunities/jobs/jobs.tsx
src/components/opportunities/mobile-opport/mob-comp/mob-comp.tsx
src/components/opportunities/mobile-opport/mob-skills-domain/mob-skilldom.tsx
src/components/opportunities/skills-domain/skilldom.tsx

path
components->opportunities
inside opportunities  there are 4 components  {company-size , skills-domain}->are filter component and jobs -> for postion jobs
components->opportunities->mobile-opport is a mobile responsve filter component 
app->oppor

opportunity+mobile responsive

---

package-lock.json
src/app/oppor/page.tsx
src/app/page/page.tsx
src/components/project-page/project-page.tsx

made change in the styling of the opportunities page
make project page side-bar 
path
components->project-page
app->page

project-pageSideBar

---

package-lock.json
src/app/addskillForm/page.tsx
src/app/educationalForm/page.tsx
src/app/market/page.tsx
src/app/market/project/page.tsx
src/app/personalinfo/page.tsx
src/components/add-skills/add-skills.tsx
src/components/educational-form/edu-form.tsx

path
components->add-skills
components->educational-form
app->addskillForm
app->educationalForm

Abhi add form skills education

---

src/app/business/businessInfo/page.tsx
src/components/BusinessSidebar.tsx

Added BusinessInfo Profile component and form

BusinessInfo 

---

src/app/dashboard/freelancer/page.tsx
src/app/dashboard/page.tsx
src/app/dashboard/talent/page.tsx

path
app->dashboard->talent
not accepting domain values

talent-Page

---

src/app/freelancer/project/page.tsx
src/components/freelancer/project/projectDetailCard.tsx
src/components/freelancer/project/projectProfileDetailCard.tsx

Description:
1) made freelancer project profiles info page

freelancer project profiles info

---

package-lock.json
src/app/dashboard/freelancer/interview/current/page.tsx
src/app/dashboard/freelancer/interview/history/page.tsx
src/app/dashboard/freelancer/interview/layout.tsx
src/app/dashboard/freelancer/interview/page.tsx
src/app/dashboard/freelancer/interview/profile/page.tsx
src/components/form/profileForm.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx
src/config/menuItems/freelancer/interviewMenuItems.tsx

Added Skills and domain from api and display it in badge
Created Interview Section with profile , current and history pages

Added Interview Section of Freelancer

---

package-lock.json
package.json
src/app/market/freelancer/page.tsx
src/app/oracleDashboard/businessVerification/page.tsx
src/app/oracleDashboard/educationVerification/page.tsx
src/app/oracleDashboard/projectVerification/page.tsx
src/app/oracleDashboard/workExpVerification/page.tsx
src/components/cards/oracleDashboard/businessVerificationCard.tsx
src/components/cards/oracleDashboard/educationVerificationCard.tsx
src/components/cards/oracleDashboard/projectVerificationCard.tsx
src/components/cards/oracleDashboard/workExpVerificationCard.tsx
src/components/ui/radio-group.tsx

Description: 
1) implemented education verification page
2) implemented project verification page
3) implemented workExp verification page
4) implemented business verification page

implement oracle dashboard verification pages - education, project, workExp, business

---

src/components/dash-comp/talentForm/skilldomainForm.tsx

add status and fix toggle button in talent page
path
app->dashboard->freelancer->talent

Abhi new talentpage

---

package-lock.json
package.json
src/components/dash-comp/talentForm/skilldomainForm.tsx
src/components/ui/switch.tsx

change in talent page toggle button

talent form toggle button

---

src/app/dashboard/freelancer/interview/current/page.tsx
src/app/dashboard/freelancer/interview/history/page.tsx
src/app/dashboard/freelancer/interview/layout.tsx
src/app/dashboard/freelancer/interview/page.tsx
src/app/dashboard/freelancer/interview/profile/page.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx

Reverts dehixorg/dehix_alpha_frontend#66

Revert "Newchirag/interview"

---

src/app/home/about/page.tsx
src/app/home/testimonial/page.tsx
src/app/market/freelancer/page.tsx
src/app/market/freelancer/project/page.tsx
src/app/project/page.tsx

Description:
1) make pages responsive
path:
1) /home/about
2) /home/testimonial
3) /project
4) /market/freelancer/project

make pages responsive

---

src/app/business/project/page.tsx
src/app/dashboard/freelancer/interview/current/page.tsx
src/app/dashboard/freelancer/interview/history/page.tsx
src/app/dashboard/page.tsx
src/components/newcomp-test/act-proj/active-card.tsx
src/components/newcomp-test/pen-proj/pending-card.tsx

Description:
1) made dashboard and its pages responsive
path:
/dashboard
/dashboard/freelancer/interview/history
/dashboard/freelancer/interview/current
/dashboard/freelancer/interview/profile
/business/project

make dashboard and its pages responsive

---

src/app/dashboard/freelancer/interview/profile/page.tsx
src/app/market/business/page.tsx
src/app/market/freelancer/page.tsx
src/app/market/freelancer/project/page.tsx
src/components/dash-comp/talentForm/skilldomainForm.tsx
src/components/form/profileForm.tsx

Description:
1) made market folder pages responsive
path:
/market/business
/market/freelancer

made market pages responsive

---

src/components/customFormComponents/multiselect.tsx
src/components/form/businessCreateProjectForm.tsx

Description:
1) integerate domain and skills api in business add project form
path
/business/add-project

integerate domain and skills api in add project form

---

src/app/dashboard/freelancer/interview/profile/page.tsx
src/app/dashboard/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/dashboard/freelancer/page.tsx

add hamburger icon to  app->dashboard->freelancer->interview->history->page.tsx
add overflow to table in :
app->dashboard->freelancer->page.tsx
app->dashboard->freelancer->interview->profile

Abhi bugs fix

---

src/app/settings/personal-info/page.tsx
src/app/settings/support/page.tsx
src/components/shared/DropdownProfile.tsx
src/config/menuItems/freelancer/supportMenuItems.tsx

add support page
add link to profile-dropdown menu (setting, support)
path:
http://localhost:3000/settings/support
app->settings->support

add support page

---

package-lock.json
src/app/freelancer/[freelancer_id]/freelancer-info/page.tsx

created a freelancer info page
/freelancer/[freelancer_id]/freelancer-info

freelancer info page

---

src/app/dashboard/business/talent/HireTalent1/page.tsx
src/app/settings/business-info/page.tsx
src/app/settings/support/page.tsx
src/config/menuItems/freelancer/supportMenuItems.tsx

fix business bugs
add logout to business setting
fix support page -> breadcrumb 
update talent page

fix-bugs-modify-talentPage

---

src/components/form/businessCreateProjectForm.tsx

fix  business-addProject-form
add project m click krke jese hi project add hoga form clear ho jaye ga
freelancer ke liye condition lga di hai minimum =1
rate ke liye condition lga di hai minimum 0
taki negative value select na kre
path:
components->form->businessCreateProjectForm.tsx

changes in business addProject form

---

src/components/dialogs/addEduction.tsx
src/components/dialogs/addExperiences.tsx
src/components/dialogs/addProject.tsx

fix bugs of 
settings/professional-info
settings/projects
settings/education-info

Fixed Bugs of dates

---

src/app/market/freelancer/page.tsx

mobile view filter is not hide when switch from mobile view to desktop view
make mobile view filter scrollable and move apply button to bottom

Tushar-bug-fix

---

src/app/dashboard/business/page.tsx
src/app/dashboard/business/talent/HireTalent1/page.tsx
src/app/dashboard/freelancer/interview/profile/page.tsx
src/app/project/[project_id]/page.tsx

fix bugs sheet bug {54,55}
add packageOpen to required pages
fix table color of freelancer

add background to pages{packageOpen},fix freelancer table

---

src/app/market/business/page.tsx
src/app/market/freelancer/page.tsx

fix market sidebar in freelancer-business
path
market->freelancer
market->business

fix market sidebar in freelancer-business

---

src/app/business/add-project/page.tsx
src/app/project/applied/page.tsx
src/app/project/completed/page.tsx
src/app/project/current/page.tsx
src/app/project/rejected/page.tsx
src/app/settings/education-info/page.tsx

in drop-down support button is not working
path: settings/education-info
{no option of freelancer is added in breadcrumb in project }
old component is replaced with new component  of dropdownProfile

Abhi fix bugs2

---

src/components/form/profileForm.tsx

Description: 
1) Added domain dropdown in freelancer personal info page
path:
/settings/personal-info

add domain dropdown freelancer personal info

---

src/app/page.tsx
src/components/form/register/freelancer.tsx

Description:
1) fixed the freelancer register bug
2) redirect to login functionality

fix freelancer register bug

---

src/app/auth/login/page.tsx
src/components/form/register/freelancer.tsx

Proper message for invalid credentials and signup.
path: src\components\form\register\freelancer.tsx
path: src\app\auth\login\page.tsx

Proper message for invalid credentials and signup

---

src/app/market/freelancer/page.tsx
src/components/cards/educationInfoCard.tsx
src/components/opportunities/skills-domain/skilldom.tsx

remove filter from market free lancer 
{ filter by location and type has been remove}
fix education card {text is visible now }

Abhi remove filter

---

src/app/business/market/page.tsx
src/components/business/market/FilterSideBar.tsx
src/components/business/market/FreelancerList.tsx
src/components/business/market/MarketHeader.tsx
src/components/business/market/MobileFilterModal.tsx

Formatted code for market page 
path : src\app\business\market\page.tsx
components added : src\components\business\market\FilterSideBar.tsx
src\components\business\market\FreelancerList.tsx
src\components\business\market\MarketHeader.tsx
src\components\business\market\MobileFilterModal.tsx

Code Formatting

---

src/components/shared/DropdownProfile.tsx
src/config/menuItems/business/settingsMenuItems.tsx
src/config/menuItems/freelancer/interviewMenuItems.tsx
src/config/menuItems/freelancer/oracleMenuItems.tsx
src/config/menuItems/freelancer/projectMenuItems.tsx
src/config/menuItems/freelancer/settingsMenuItems.tsx

Description: positioned home button in sidebar and  profile dropdown component

positioned home button in sidebar and  profile dropdown component

---

src/config/menuItems/freelancer/dashboardMenuItems.tsx

fix setting button

---

src/app/freelancer/market/page.tsx
src/components/business/market/FilterSideBar.tsx
src/components/business/market/FreelancerList.tsx
src/components/business/market/MarketHeader.tsx
src/components/business/market/MobileFilterModal.tsx

fix position of filter of market in freelancer and business
fix styling of business market filter in mobile view

fix filter in market

---

src/app/not-found.tsx

Description:
1) implemented the not-found 404 page which redirects to dashboard of freelancer and business respectively after some time - 1.5s

handle 404 page for freelancer and business

---

package-lock.json
src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/components/cards/oracleDashboard/businessVerificationCard.tsx
src/components/cards/oracleDashboard/educationVerificationCard.tsx
src/components/cards/oracleDashboard/projectVerificationCard.tsx
src/components/cards/oracleDashboard/workExpVerificationCard.tsx
src/components/ui/switch.tsx
src/components/ui/toggle.tsx
src/dummydata.json

only get api is connected ,  no change in design because  receiving empty array from backend

Aayush oracle verification get api

---

src/app/freelancer/market/page.tsx
src/components/opportunities/jobs/jobs.tsx

path:http://localhost:3000/freelancer/market
api connected to update not interested array of project

Aayush not interested project api connect

---

src/app/AuthContext.tsx
src/app/bidmanagement/page.tsx
src/app/business/add-project/page.tsx
src/app/business/market/page.tsx
src/app/business/talent/page.tsx
src/app/freelancer/interview/current/page.tsx
src/app/freelancer/market/page.tsx
src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/app/freelancer/settings/education-info/page.tsx
src/app/page.tsx
src/components/bidmanagement/biditem.tsx
src/components/cards/oracleDashboard/businessVerificationCard.tsx
src/components/cards/oracleDashboard/educationVerificationCard.tsx
src/components/cards/oracleDashboard/projectVerificationCard.tsx
src/components/cards/oracleDashboard/workExpVerificationCard.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/form/profileForm.tsx
src/components/form/register/freelancer.tsx
src/components/opportunities/jobs/jobs.tsx
src/components/shared/otpDialog.tsx
src/config/menuItems/freelancer/supportMenuItems.tsx

fix all lint warning and error

Tushar lint fix

---

package-lock.json
src/app/freelancer/project/[project_id]/page.tsx
src/components/form/profileForm.tsx
src/components/freelancer/project/projectDetailCard.tsx
src/components/freelancer/project/projectProfileDetailCard.tsx
src/components/opportunities/freelancer/freelancerCard.tsx
src/components/opportunities/jobs/jobs.tsx

add on's-selected options are removed from the list, project domain option is added(didn't added data),freelancer card is oriented

freelance card

---

src/components/form/businessCreateProjectForm.tsx

Adding a a new field "project Domain" in a  buisness add-project [http://localhost:3000/business/add-project](url)

Adding project domain in add-project

---

src/components/freelancer/project/projectProfileDetailCard.tsx
src/components/freelancer/talent/domainDiag.tsx
src/components/freelancer/talent/skillDiag.tsx
src/components/freelancer/talent/skilldomainForm.tsx

integrate api on dehix talent frontend
http://localhost:3000/freelancer/talent

DHH-2: Integrates dehix talent api and freelancerDehixTalent toggle update

---

src/components/form/profileForm.tsx

profilfrom-api-integration in project-domain

---

src/app/freelancer/market/page.tsx

fix projectDomain filter in freelancer market place
http://localhost:3000/freelancer/market

DF-62: Fixes projectDomain filter in freelancer market place

---

src/middleware.ts

ADD to two more protected route /freelancer and /business so that they both not access each other

Df 73/add protected route/isha

---

package-lock.json
src/app/freelancer/scheduleInterview/page.tsx
src/components/freelancer/scheduleInterview/scheduleInterviewDialog.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx
src/hooks/use-toast.ts
src/utils/freelancer/enum.ts

DF-60: Created schedule interview page

---

src/components/business/hireTalent.tsx/domainDiag.tsx
src/components/business/hireTalent.tsx/skillDiag.tsx
src/components/business/projectSkillCard.tsx
src/components/freelancer/homeTableComponent.tsx
src/components/freelancer/project/projectDetailCard.tsx
src/components/opportunities/jobs/jobs.tsx
src/utils/statusBadge.ts

added a newfilefor Projectstatus in utils folder
added the badges in the status section of the freelancer Dashboard

DF-79: Added badges to all the status in whole Dashboard

---

src/app/business/project/[project_id]/page.tsx
src/components/freelancer/project/bidDialog.tsx
src/components/freelancer/project/bidsDetail.tsx
src/components/freelancer/project/bidsDetailTable.tsx

Df 18 bids in business abhi

---

src/components/form/profileForm.tsx

added the Description in http://localhost:3000/freelancer/settings/personal-info with limited to 500 count

DF-80: Added Description in freelancer model not more that 500 character count

---

src/app/freelancer/market/page.tsx
src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/app/freelancer/project/applied/page.tsx
src/app/freelancer/project/completed/page.tsx
src/app/freelancer/project/current/page.tsx
src/app/freelancer/project/rejected/page.tsx
src/components/business/hireTalent.tsx/skillDomainForm.tsx
src/components/business/market/MarketHeader.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/freelancer/scheduleInterview/scheduleInterviewDialog.tsx
src/components/freelancer/talent/skilldomainForm.tsx

DF-90: Added table Name and description above all tables

---

src/app/business/settings/business-info/page.tsx
src/app/business/talent/page.tsx
src/app/dashboard/business/page.tsx
src/app/dashboard/freelancer/page.tsx
src/app/freelancer/[freelancer_id]/freelancer-info/page.tsx
src/app/freelancer/interview/current/page.tsx
src/app/freelancer/interview/history/page.tsx
src/app/freelancer/market/page.tsx
src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/app/freelancer/project/applied/page.tsx
src/app/freelancer/project/completed/page.tsx
src/app/freelancer/project/current/page.tsx
src/app/freelancer/project/rejected/page.tsx
src/app/freelancer/scheduleInterview/page.tsx
src/app/freelancer/settings/education-info/page.tsx
src/app/freelancer/settings/personal-info/page.tsx
src/app/freelancer/settings/professional-info/page.tsx
src/app/freelancer/settings/projects/page.tsx
src/app/freelancer/talent/page.tsx
src/components/search.tsx

Made the use of search.tsx file in components....as it was made but not efficiently used in all pages...

DF:75 Made the breadcrumbs and search container fixed in all pages

---

src/app/business/market/page.tsx
src/app/freelancer/market/page.tsx
src/components/menu/collapsibleSidebarMenu.tsx
src/components/opportunities/freelancer/freelancerCard.tsx
src/components/opportunities/jobs/jobs.tsx
src/components/opportunities/jobs/profileCard.tsx

DF-95:Responsive for all device in page themetoggle-business-freelancer-page(mobileview)

---

src/app/bidmanagement/page.tsx
src/app/business/project/[project_id]/page.tsx
src/app/consultancy/[freelancer_id]/page.tsx
src/app/dashboard/business/page.tsx
src/app/freelancer/market/page.tsx
src/app/freelancer/project/[project_id]/page.tsx
src/components/bidmanagement/biditem.tsx
src/components/cards/projectCard.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/form/register/freelancer.tsx
src/components/freelancer/project/bidsDetail.tsx
src/components/opportunities/jobs/profileCard.tsx

changed the api name from business to project in the prefix.........

DF:108: Changed in the apis of project from business prefix to project

---

src/app/freelancer/project/[project_id]/page.tsx
src/components/menu/sidebarMenu.tsx

->In sidebarmenu when click on market icon then it not redirect on market place from project id page.
->On place of loader only plain text is shown

Bug:Df-94 Loder and sidebar bug in  business profile 

---

src/app/freelancer/market/page.tsx
src/components/opportunities/jobs/jobs.tsx

DF-116:changes design of freelancer market

---

src/app/freelancer/interview/current/page.tsx
src/app/freelancer/interview/history/page.tsx
src/app/freelancer/market/page.tsx
src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/app/freelancer/scheduleInterview/page.tsx
src/app/freelancer/settings/personal-info/page.tsx
src/app/freelancer/talent/page.tsx
src/components/business/hireTalent.tsx/skillDomainForm.tsx
src/components/business/market/MarketHeader.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/freelancer/scheduleInterview/scheduleInterviewDialog.tsx
src/components/freelancer/talent/skilldomainForm.tsx
src/components/ui/dialog.tsx

DF:137 Adjusted Breadcrums, Titles, Dialog Box cross buttons 

---

src/components/business/hireTalent.tsx/skillDomainForm.tsx
src/components/business/hireTalent.tsx/talentCard.tsx

- it gives error when no data found in hire table
- give error in talent cards if no more talent cards are there

DF-101: Error handling in hire dehix talent page

---

src/app/freelancer/market/page.tsx
src/components/freelancer/project/projectProfileDetailCard.tsx
src/components/opportunities/jobs/jobs.tsx
src/components/opportunities/jobs/profileCard.tsx

add not interested project filter in freelancer market place
check already applied bid and change the button text bid to applied

DF-142: Add not interested filter and already applied bid

---

src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/freelancer/talent/skilldomainForm.tsx

add skeleton on dehix-talent and interview page of freelancer page

add skeleton on dehix-talent and interview page 

---

src/components/freelancer/homeTableComponent.tsx
src/config/menuItems/freelancer/interviewMenuItems.tsx
src/config/menuItems/freelancer/oracleMenuItems.tsx
src/config/menuItems/freelancer/projectMenuItems.tsx

add a setting icon while clicking on projects ,interview and verifcation on freelancer page and type Head remove from dasboard freelancer table

 setting icon is showring while  we click on projects on freelancer page 

---

src/app/settings/support/page.tsx
src/app/settings/support/supportTicketFofm.tsx
src/app/settings/support/supportTicketForm.tsx

DF-153[WIP]:Support ticket form

---

src/app/business/freelancerProfile/[freelancer_id]/page.tsx
src/components/business/hireTalent.tsx/talentCard.tsx
src/components/dialogs/skillDialog.tsx
src/components/freelancer/project/bidsDetail.tsx
src/components/opportunities/jobs/jobs.tsx
src/components/opportunities/mobile-opport/mob-comp/mob-comp.tsx

intially the profile of the freelancer was not able to be fetched so corrected the call of api

SP3-49: Added freelancer_id in fetching the details in profile view of freelancer in business

---

src/components/dialogs/addEduction.tsx
src/components/dialogs/addExperiences.tsx
src/components/dialogs/addProject.tsx

set limit in date of education info, experience and projects

SP3-45: Form validation set max limit in date of education info, experience and projects

---

src/components/dialogs/domainDialog.tsx
src/components/dialogs/skillDialog.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx

fix form's open and submit in add skill and add domain of interview profile

SP3-51: Fixes form's open and submit in 'add skill' and 'add domain' of interview profile

---

src/country-codes.json

SP3-53: Add country name for signup form

---

src/components/form/profileForm.tsx

In freelancer personal info there is a project domain added but it can not be deleted when click on cross.

DF-165[BUG]:Project domain not deleted bug fix

---

package-lock.json
package.json
src/components/form/businessCreateProjectForm.tsx

add limit in per-hour-rate, experience, min freelancer required and remove loading from create project button businessCreateProjectForm

Vansh/sp3 59/add limit in form

---

src/app/freelancer/market/page.tsx

fix getProject api call in freelancer marketplace

fix getProject api call in freelancer marketplace

---

src/app/business/project/[project_id]/page.tsx

SP3-25: Adds status change button for Projects

---

src/components/form/businessCreateProjectForm.tsx

add remove button in URL, remove loading from create project button

Vansh/sp3 63/fixing the url button

---

src/app/dashboard/business/page.tsx
src/components/business/hireTalent.tsx/talentCard.tsx
src/components/form/businessForm.tsx

add link to button instead of text and reset save changes button after saving the data

Vansh/sp3 68/add link to button instead of text

---

src/app/business/project/[project_id]/page.tsx
src/app/dashboard/freelancer/page.tsx
src/app/freelancer/project/[project_id]/page.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/freelancer/homeTableComponent.tsx
src/components/freelancer/project/projectDetailCard.tsx
src/utils/freelancer/enum.ts

fix create project form data and fix problem of same skills across different profiles in create project form
correct naming domain to projectDomain in projectDetailCard and made minor changes in design like position of project status, display flex in skills etc.
update project interface as updated in backend
fix projectTable in freelancer dashboard

Tushar/project fix (ticket id: DF-152)

---

src/components/dialogs/addExperiences.tsx
src/components/dialogs/addProject.tsx
src/components/form/businessForm.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

apply checks on github and linkedin in forms

Vansh/sp3 69/implement linked in field validation with url structure

---

src/middleware.ts

Fix business and freelancer path in  middleware and fix login problem with path

Vansh/sp3 71/fix business and freelancer path in  middleware

---

package-lock.json
src/app/freelancer/businessProfile/[business_id]/page.tsx

DF-166:sharable Page of  business profile

---

src/components/business/hireTalent.tsx/domainDiag.tsx
src/components/business/hireTalent.tsx/skillDiag.tsx
src/components/dialogs/domainDialog.tsx
src/components/dialogs/skillDialog.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/freelancer/scheduleInterview/scheduleInterviewDialog.tsx
src/components/freelancer/talent/domainDiag.tsx
src/components/freelancer/talent/skillDiag.tsx
src/components/opportunities/jobs/profileCard.tsx

Applying units in different fields like experience , amount etc.

Vansh/sp3 77/applying unit to different fields

---

src/app/business/Projects/page.tsx
src/app/business/add-project/page.tsx
src/app/business/freelancerProfile/[freelancer_id]/page.tsx
src/app/business/project/[project_id]/page.tsx
src/app/business/settings/business-info/page.tsx
src/app/business/talent/page.tsx
src/app/consultancy/[freelancer_id]/page.tsx
src/app/dashboard/business/talent/page.tsx
src/app/freelancer/businessProfile/[business_id]/page.tsx
src/app/freelancer/market/page.tsx
src/app/freelancer/project/applied/page.tsx
src/app/freelancer/project/completed/page.tsx
src/app/freelancer/project/current/page.tsx
src/app/freelancer/project/rejected/page.tsx
src/app/freelancer/scheduleInterview/page.tsx
src/app/freelancer/settings/education-info/page.tsx
src/app/freelancer/settings/personal-info/page.tsx
src/app/freelancer/settings/professional-info/page.tsx
src/app/freelancer/settings/projects/page.tsx
src/app/freelancer/talent/page.tsx

->Add 'header.tsx' in every page in place of dropdown , search , breadcrum, collapsesidebar.

Sp3 99:Update resuasble component header in all pages

---

src/components/form/profileForm.tsx
src/utils/DomainUtils.ts
src/utils/ProjectDomainUtils.ts
src/utils/skillUtils.ts

added a field for other options of skill, domain and project domain and add them to database

Harshit sharma/sp3 110/add a field for other option

---

package-lock.json
package.json
src/app/not-found.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

I have completed and implemented all the requested features for the custom 404 page:
Features:
- Displays a "Page not found" message.
- Dynamic button behavior based on login status:
- Logged out: Redirects to the login page.
- Logged in: Takes the user back to the previous page.
- Responsive design for mobile and desktop.
https://github.com/user-attachments/assets/1932f284-4fb5-4a81-b839-bb4191c740ea

Implement Custom 404 Page with Dynamic Button Behavior in Next.js Using ShadCN UI Components

---

src/components/form/register/business.tsx

added username for business
**this pr depends upon fastify pr named:- Harshit sharma/sp3 126/get api for username**

SP3-127: Add username input field for business signup

---

src/components/dialogs/skillDomailMeetingDialog.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx

fix api call in interview skill domain page and create dialog for create meeting

SP3-128: Skill domain interview 

---

src/app/chat/page.tsx
src/components/shared/chat.tsx
src/components/shared/chatList.tsx

-Add timestamp format and make ui better and add profile picture with every message and chat and char list last message shown.

SP3-95-[FEAT]:Add feature like emoji timestamp format and UI

---

src/components/shared/chat.tsx

SP3-131[FEAT]:Reply message feature with preview the message-isha

---

src/components/shared/chat.tsx
src/components/shared/fileAttachment.tsx

add image upload and file upload/ display feature in chat

[sp3-133]  file upload and display in chat

---

src/components/fileUpload/resume.tsx
src/components/form/profileForm.tsx

**This PR introduces the following enhancements to the /freelancer/settings/personal-info feature:**
**Updated API Body in PUT Request**
> Added projectDomain to the PUT request .
> Included enhancements for handling resume .

Sp3 152 enhancement update api put and resume functionality

---

package-lock.json
package.json
src/app/settings/support/supportTicketForm.tsx
src/components/emojiPicker.tsx
src/components/shared/NotesContainer.tsx
src/components/shared/chat.tsx
src/components/shared/chatList.tsx
src/components/shared/reactions.tsx
src/config/menuItems/freelancer/supportMenuItems.tsx

add more emojis and reactions

---

src/app/auth/sign-up/business/page.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

This PR enhances the signup stepper functionality for creating a business account with the following improvements:
- Ensures all required fields in each step are validated before moving to the next step.
- Displays error messages for incomplete or invalid fields.
- On successful account creation, users are redirected to the login page.
- Displays a success message before redirection.
- Ensures the stepper layout is fully responsive and works seamlessly across devices.
- Adjusts elements for better usability on smaller screens.
- Added a loading indicator on the "Create Account" button to show progress during account creation.
- Disabled "Next" buttons until all fields in the current step are valid.
- Validated the functionality on multiple screen sizes to ensure responsiveness.
- Tested …

[Enhancement]:Signup Stepper for Business

---

package-lock.json
src/app/auth/forgot-password/page.tsx

- Added a redirect to a confirmation screen or login page once the password reset link is successfully sent.
- Integrated a toast notification to inform users about the successful sending of the reset link.
https://github.com/user-attachments/assets/5b443aec-e0ee-43fc-86c6-06b0351a19f0
- Improved user feedback with toast notifications.
- Enhanced user flow with automatic redirection after action completion.

[Enhancement]: Added redirect and toast to reset password

---

src/components/shared/DialogSelectedNote.tsx
src/components/shared/DropdownNavNotes.tsx
src/components/shared/NotesContainer.tsx

Added a Edit icon in the note Dropdown 
updated the noteCard ,that aims  to open a dialog that shows the note details

updated dialog and added Edit icon 

---

package-lock.json
package.json
src/components/shared/chat.tsx
src/components/shared/textFormat.tsx

SP3-[FEAT]:Rich Text format using react-markdown and styling of Card

---

src/components/freelancer/talent/domainDiag.tsx
src/components/freelancer/talent/skillDiag.tsx
src/components/freelancer/talent/skilldomainForm.tsx

Rework the Dehix talent functionality and fix some issues in the frontend code
https://github.com/user-attachments/assets/7fed818c-4353-46fe-b1a1-6591b565360c

SP3 - 157 - rework on dehix-talent

---

src/app/business/freelancerProfile/[freelancer_id]/page.tsx
src/app/freelancer/market/page.tsx
src/components/business/hireTalent.tsx/talentCard.tsx
src/components/business/market/FilterSideBar.tsx
src/components/form/profileForm.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/freelancerProfile/Education.tsx
src/components/freelancerProfile/FreelancerProfileSkeleton.tsx
src/components/freelancerProfile/ProfessionalExperience.tsx
src/components/freelancerProfile/ProfileInfo.tsx
src/components/freelancerProfile/ProjectDialog.tsx
src/components/freelancerProfile/Projects.tsx
src/components/freelancerProfile/Sections.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx

**New Components Overview :** 
**Education.tsx –** Displays the freelancer's educational background with editable .
**FreelancerProfileSkeleton.tsx –** Provides a skeleton loader for profile sections .
**ProfessionalExperience.tsx –** Showcases work experience.
**ProfileInfo.tsx –** Displays profile details like name, picture, bio.
**ProjectDialog.tsx –** A modal to add/edit project details .
**Projects.tsx –** Lists completed and ongoing projects with gridviews and clickable project cards.

SP3-156 -  Freelancer-profile ui enhancement

---

src/components/form/register/freelancer.tsx
src/components/form/register/phoneNumberChecker.tsx

The name field in **FormField** was set to **"step3.phone**", which might not be correctly handled by the form, preventing the **"Create"** button from working.
**Fix: Updated the name to "phone" .**
https://github.com/user-attachments/assets/854c8e6e-ad50-4d3d-b7e5-453c0ad72fe6

business sign-up bug fix

---

src/app/globals.css
src/components/form/register/freelancer.tsx
src/components/ui/accordion.tsx
src/components/ui/checkbox.tsx
src/components/ui/dialog.tsx
src/components/ui/infinite-scroll.tsx
src/components/ui/meetingDialog.tsx
src/components/ui/skeleton.tsx

Because of **'next/router**', there was an unmounting issue.
Fix: Use **'next/navigation'.**

SP3-[BUGFIX]  Freelancer-Signup-bug-fix

---

src/app/notes/archive/page.tsx
src/app/notes/page.tsx
src/app/notes/trash/page.tsx
src/components/business/market/NotesHeader.tsx
src/components/form/register/freelancer.tsx
src/components/shared/CreateNoteDialog.tsx
src/components/shared/DropdownNavNotes.tsx

notes ui changes and render improvement

notes rendering improve

---

src/components/form/businessForm.tsx
src/components/form/profileForm.tsx
src/components/form/register/freelancer.tsx

business freelancer profile-info add readonly for username email and …

SP3-163 business freelancer profile-info add readonly 

---

src/components/dialogs/addExperiences.tsx
src/components/dialogs/addProject.tsx
src/components/shared/DropdownProfile.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx
src/config/menuItems/freelancer/projectMenuItems.tsx

change name "rejected verified" to "rejected project"
change name "scheduleInterviews" to "schedule interview"
fix payload value in freelancer experience
fix payload parameter and value in freelancer projects

Tushar hotfix

---

src/utils/enum.ts

Update enum values to uppercase for consistency
After updating the enum values, it is working correctly.
https://github.com/user-attachments/assets/b2afdb7d-3bb5-4167-9f9a-6dd296f74b6f

SP3-[BUG-FIX] for freelancer/profileInfo while adding custom skill and domain..

---

src/app/auth/login/page.tsx
src/components/dash-comp/profile-completion/page.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

1. Added “Create Your Business account” which was not there during registration.
2. Added margin for add url button in add-project
3. Added a description for min-Connect
4.Changed description to Profile Description

[BUGS]:Resolved bugs from the bug sheet provided

---

src/app/dashboard/freelancer/page.tsx
src/components/dash-comp/profile-completion/page.tsx
src/components/form/profileForm.tsx

This PR introduces the following updates to the profile page:
1. Profile Progress Bar: A progress bar has been added to visually represent the completion percentage of the user’s profile. It dynamically updates based on the profile completion data.
2. Redirect to Update Profile Page: When the user clicks on the "Complete Profile" button, they are now redirected to the update profile page to finish filling out their information.
3. Skeleton Loader: A skeleton loader has been added to improve the user experience while the profile completion percentage or API data is loading.
Changes:
1. Added a progress bar component that displays the current profile completion.
2. Implemented redirection logic for the "Complete Profile" button.
3. Introduced skeleton loading states to indicate loading …

[Feature]:Added profile progressbar for freelancer

---

src/components/fileUpload/profilePicture.tsx
src/components/form/profileForm.tsx

The "add" button is disabled until a skill , domain and projectDomain is chosen
and add minus minus icon for deselecting/removing the uploaded image
https://github.com/user-attachments/assets/4b72b157-6ca3-47e3-84c4-8ae656dd17fd
updated 
https://github.com/user-attachments/assets/5ccc34e0-4811-4002-bc32-53fe72af2545

code fix and added minus icons to deselect updated profile image

---

src/components/form/profileForm.tsx
src/components/freelancer/talent/skilldomainForm.tsx
src/utils/common/getBadgeStatus.tsx

Encountered an error:
"Cannot read properties of undefined (reading 'toLowerCase')".
FIX - Added optional chaining to prevent errors when accessing undefined values. 
flattening the talentData array caused issues — it was not rendering correctly.
fixed final SS
profileForm errors 
the error of undefine
**We were using data instead of data.data, which caused the error.** 
and some small  issue that after adding same skills/project/domain i can add it again , has been fixed

SP3-[BUGFIX] for freelancer-dehix-talent page

---

src/components/dropdown/user.tsx
src/components/form/register/freelancer.tsx

There were few errors like redefining of hooks multiple times and also incorrect comparision between enum so these were the errors which were causing build errors so this pr solves the issue

solved the errors which were causing build errors

---

package-lock.json
package.json
src/app/business/project/[project_id]/page.tsx
src/app/dashboard/business/page.tsx
src/components/freelancer/project/bidsDetail.tsx
src/components/ui/carousel.tsx

Added carousel on the business Dashboard

Added-carosuels

---

src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

https://github.com/user-attachments/assets/683f435d-2ba1-43ec-b81a-4090bb4b96fb

SP3-171-business-freelancer form fix

---

src/app/settings/support/supportTicketForm.tsx

Button appylied to switch view mode of tickets in card and table mode and save cards after refresh

[feature]-Apply-Different-view-button-to-show-tickets-in-different-modes

---

src/components/header/header.tsx
src/components/shared/DropdownProfile.tsx

Actually, there was an error showing 'undefined' because I forgot to use response.data.data and instead, I only used resp.data .

SP3-161- dehix-connects-issue

---

src/app/freelancer/project/[project_id]/milestone/page.tsx
src/app/freelancer/project/applied/page.tsx
src/app/freelancer/project/completed/page.tsx
src/app/freelancer/project/current/page.tsx
src/app/freelancer/project/rejected/page.tsx
src/app/globals.css
src/components/cards/projectCard.tsx
src/components/header/header.tsx
src/components/shared/MilestoneCards.tsx
src/components/shared/MilestoneTimeline.tsx
src/config/menuItems/freelancer/projectMenuItems.tsx

Updates for Project Pages:
1. Added a loader component.
2. Corrected API calls following recent updates.
3. Restored styles in global.css as they were previously removed.
4. Added an empty bucket icon in the Milestone section when no milestones are created.
5. Make sure all height of cards is same set h-[400px]
Milestone Header UI Fix:
Before
After

SP3-173-project-page-fix

---

src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

Added get username api and loader
https://github.com/user-attachments/assets/abf85bce-6780-44ac-b315-9cf258209957

SP3-171-get-user-by-userName-api-added

---

src/app/settings/support/page.tsx
src/app/settings/support/supportTicketForm.tsx

Added a loader during data creation, updates, and loading processes. Improved overall UI for better user experience.
BEFORE
AFTER
https://github.com/user-attachments/assets/8e1b0c51-dada-4df1-b546-157d5a3bf1d3

SP3-181 ticket Page testing

---

src/app/settings/support/page.tsx
src/app/settings/support/supportTicketForm.tsx
src/components/accordian/faqAccordian.tsx
src/config/menuItems/freelancer/supportMenuItems.tsx

1.  Changed "your" to "our" (no "where applicable") as per the bug sheet.
2. Added a temporary handleSubmit function to show a success message.
3. Ensured toast API integration is yet to be added.
4. Fixed the "Home" icon href navigation for freelancer

SP3-177-Bug-fixes

---

src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx

Added a referral input field to the form.  
Backend PR - https://github.com/dehixorg/dehix_fastify/pull/269
Fixed date validation issue by using `.union([z.string(), z.date()])` to match backend expectations.  
- string as to prevent null error

SP3-198-business-referral-rework

---

src/app/bidmanagement/page.tsx
src/app/freelancer/interview/profile/page.tsx
src/components/business/hireTalent.tsx/talentCard.tsx
src/components/form/resumeform/SkillInfo.tsx
src/components/form/resumeform/SummaryInfo.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/header/header.tsx

sir i have solved most of the linting issues and there are 2 more warnings to solve and i think the useState dependencies are for future use so i left them as it is.

[Fix]:Fixed linting issues

---

src/components/business/hireTalent.tsx/talentCard.tsx
src/components/dialogs/addEduction.tsx
src/components/dialogs/addExperiences.tsx
src/components/dialogs/addProject.tsx
src/components/form/businessCreateProjectForm.tsx
src/components/header/header.tsx
src/components/shared/ConnectsDialog.tsx
src/components/shared/DraftDialog.tsx
src/hooks/useDraft.ts

https://github.com/user-attachments/assets/a1f621ff-061b-4714-bfd8-c1ab4c183f2c
https://github.com/user-attachments/assets/111b61b2-cc41-4e64-8096-e418b349cbad
https://github.com/user-attachments/assets/c4af945a-ad3d-4216-9c0b-77ad9b7978a3
https://github.com/user-attachments/assets/dbfaba0b-9232-40f8-b413-13fa9ebabbdd

SP3-199- Draft feature added

---

src/components/form/businessCreateProjectForm.tsx

https://github.com/user-attachments/assets/5182be43-87a5-447b-8844-bae90748c8ba

SP3-202-business-form-rework

---

src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/projectVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/components/DateOfBirthPicker/DateOfBirthPicker.tsx
src/components/fileUpload/resume.tsx
src/components/form/profileForm.tsx
src/components/form/register/livecapture.tsx

This pr solves the api errors in oracle page.

[BUGS]:Freelancer Oracle bugs

---

src/components/business/hireTalent.tsx/talentCard.tsx

https://affine.dehix.org/workspace/b6796785-fa00-40df-ade0-63f12420e7fa/P3fOOC1xS5U4s4YgSxBuW?databaseId=Z9yKcX3c8ZMezrTIUSy51&databaseDocId=EemxgxBnjxr37_71gh3Pm&databaseRowId=qFwynOMCLTVTBcw36UdZ5

Changed the hire dehix talent in business

---

src/app/business/freelancerProfile/[freelancer_id]/page.tsx

enhanced profile card

---

src/app/AuthContext.tsx
src/app/globals.css
src/components/business/market/MobileFilterModal.tsx
src/components/shared/OfflinePage.tsx
src/utils/NetworkProvider.tsx

Uploading Dehix - Google Chrome 2025-03-11 14-06-27.mp4…

SP3-205-offline page updates

---

src/components/dialogs/skillDomailMeetingDialog.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx

SP3 211 interview bug fix

---

src/app/auth/login/page.tsx
src/app/business/settings/business-info/page.tsx
src/app/business/settings/kyc/page.tsx
src/app/freelancer/settings/education-info/page.tsx
src/app/freelancer/settings/kyc/page.tsx
src/app/freelancer/settings/personal-info/page.tsx
src/app/freelancer/settings/professional-info/page.tsx
src/app/freelancer/settings/projects/page.tsx
src/app/freelancer/settings/resume/page.tsx
src/app/notes/archive/page.tsx
src/app/notes/page.tsx
src/app/notes/trash/page.tsx
src/components/dialogs/skillDomailMeetingDialog.tsx
src/components/form/businessForm.tsx
src/components/form/kycBusinessForm.tsx
src/components/form/kycForm.tsx
src/components/form/kycFreelancerForm.tsx
src/components/form/profileForm.tsx
src/components/freelancer/interviewProfile/interviewProfile.tsx
src/components/menu/sidebarMenu.tsx
src/components/shared/otpDialog.tsx
src/config/menuItems/business/settingsMenuItems.tsx
src/config/menuItems/freelancer/settingsMenuItems.tsx

BEFORE
https://github.com/user-attachments/assets/d6618828-f3e3-4f27-adcb-ec589899b368
AFTER
https://github.com/user-attachments/assets/61381d96-c9cc-4774-b809-8fa6fb31b6cc
KYC page disable if applied
https://github.com/user-attachments/assets/577037d0-c970-4648-bd42-583d3c44cb5d

SP3-212- kyc module update

---

src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/educationVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/components/cards/oracleDashboard/businessVerificationCard.tsx

the array was not flat properly
updated but result is coming empty

SP3-207-oracle-fix

---

src/app/freelancer/oracleDashboard/businessVerification/page.tsx
src/app/freelancer/oracleDashboard/workExpVerification/page.tsx
src/components/form/kycFreelancerForm.tsx
src/components/form/profileForm.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx
src/components/menu/sidebarMenu.tsx
src/components/shared/BusinessTermsDialog.tsx
src/components/shared/FreelancerTermsDialog.tsx

https://github.com/user-attachments/assets/1388d79c-e012-4f8e-a9f7-53e4624a3306
https://github.com/user-attachments/assets/20c4c558-3b65-4f08-8b0c-4a831590565d

SP3-214-terms and conditions

---

src/components/shared/otpDialog.tsx

https://github.com/user-attachments/assets/b403daa3-b7ac-4ffb-8f69-5becf9d92e8e

SP3-215-login-fix

---

src/app/chat/page.tsx
src/components/header/header.tsx
src/components/menu/collapsibleSidebarMenu.tsx
src/components/menu/sidebarMenu.tsx
src/components/shared/chat.tsx
src/components/shared/fileAttachment.tsx
src/config/menuItems/freelancer/dashboardMenuItems.tsx

ONLY THE COLOR COMBINATION NEEDS TO BE FIXED, EVERYTHING ELSE IS DONE.
The reply icon for the sender has been moved to its message container. 
https://github.com/user-attachments/assets/4c364d57-f2ac-49da-b753-c18727a377b8
Bug Fix: When I react to an emoji, the chat scrolls to the bottom.
https://github.com/user-attachments/assets/3e620c97-2e0e-4072-87fb-7c88e4e094e4
https://github.com/user-attachments/assets/f549cccd-c4fd-40a9-98bb-51ee9788c683
Updates
FINAL VERSION

SP3-217-Chat-UI-Rework

---

src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx
src/components/shared/BusinessTermsDialog.tsx
src/components/shared/FreelancerTermsDialog.tsx

**Issue: Checkbox State Not Updating Correctly in TermsDialog**

SP3-220-bug-fix

---

package-lock.json
src/app/chat/page.tsx
src/components/dialogs/skillDomailMeetingDialog.tsx
src/components/form/register/business.tsx
src/components/form/register/freelancer.tsx
src/components/menu/sidebarMenu.tsx
src/components/shared/chat.tsx

Done some changes to fix small issues.

---

src/components/dialogs/addProject.tsx

Implemented handleAddSkill to update form state and clear input

Fix: Enable project creation by properly handling techUsed skills input

---

src/app/freelancer/interview/current/page.tsx
src/components/freelancer/bids/BidList.tsx
src/components/freelancer/bids/Bids.tsx
src/components/freelancer/talent/domainDiag.tsx
src/components/freelancer/talent/skillDiag.tsx
src/components/freelancer/talent/skilldomainForm.tsx

1. Interview Bids Page Improvements
. Display Talent Type:
The bids accordion now shows the talentType for each interview instead of the generic "No Talent Label".
.  Improved Empty State Messaging:
In the BidList component, if an interview has no bids, it now displays: "No bids are available for the interview".
2. Talent Management Dialogs and Form
. Skill Dialog (skillDiag.tsx):
. Improved form validation and error handling.
. Ensured the dialog closes and resets after successful submission.
. Updated toast messages for better user feedback.
. Ensured the correct skill is removed from the list after adding.
. Domain Dialog (domainDiag.tsx):
. Improved domain selection and form validation.
. Enhanced error handling and user feedback.
. Ensured the correct domain is removed from the list …

Update bids and bid list UI, and fixed bugs in the dehix talent 

---

src/components/custom-table/CustomTable.tsx
src/components/custom-table/FieldComponents.tsx
src/components/custom-table/FieldTypes.ts
src/components/freelancer/project/bidsDetail.tsx

Created a table for showing bids for project made by the freelancers at the business profile 

---

src/components/custom-table/CustomTable.tsx
src/components/custom-table/FieldComponents.tsx
src/components/custom-table/FieldTypes.ts
src/components/freelancer/project/bidsDetail.tsx

In the previous pr after merging there were some bugs for the production like importing order bugs etc those are fixed now and functionality is same as previous

Fix the errors and bugs for the production 

---

src/app/bidmanagement/page.tsx
src/components/form/resumeform/Achievement..tsx
src/components/form/resumeform/EducationInfo.tsx
src/components/form/resumeform/GeneralInfo.tsx
src/components/form/resumeform/PersonalInfo.tsx
src/components/form/resumeform/SkillInfo.tsx
src/components/form/resumeform/SummaryInfo.tsx
src/components/form/resumeform/WorkExperienceInfo.tsx
src/components/resumeEditor/ResumePreview1.tsx
src/components/resumeEditor/ResumePreview2.tsx
src/components/resumeEditor/atsScore.tsx
src/components/resumeEditor/page.tsx
src/components/ui/AddButton.tsx
src/constants/resumeAnalysis.ts

Fixes-
1. Changed Template1, Template2 and DownloadPDF button and placed it on the top right corner of the resumepreview.
2. Added show/hide toggle section for resume sections like summary ,achievements ,etc.
3. Fixed the PDF that was being generated by downloadpdf function so that if a resume is of multiple pages, then all of those pages should be generated in the final pdf.
4. Made the plus button full length.
5. Removed the re-analyze resume button 
6. Removed the multiple color font option.
7. Improved ats scoring standards.
8. Aligned all the components of the left and right section of the page

Fixed resume editor

---

src/components/shared/ProjectApplicationPage.tsx

Added the freelancer profiles at the applying project page

---

src/app/business/project/[project_id]/page.tsx
src/app/freelancer/market/page.tsx
src/components/freelancer/project/projectDetailCard.tsx
src/components/shared/JobCard.tsx
src/components/shared/ProjectApplicationPage.tsx

fixed my fixes like not interested projects will not show on the marketplace.
Added a filter for the favourites projects.
improved the profile selection process.

Fixed many small issues

---

src/app/reports/page.tsx
src/components/form/ReportForm.tsx
src/components/report-tabs/PastReportsTab.tsx

1)Fixed an Issue where report section was not responding to dark mode
2)Fixed image width not coming issue on reportform
3)Fixed business breadcrump and menu  whre freelancer menu was coming

Report bug fixes on alpha  Part 1

---

src/components/cards/projectCard.tsx
src/components/shared/JobCard.tsx

1. Replaced the custom dropdown implementation with shadcn/ui’s <DropdownMenu> component
2. Removed manual menuOpen state and click-outside logic
3. Ensured the dropdown no longer overlaps the trigger (3-dot menu)
**Tested locally to confirm correct open/close behavior**

Fix report button issues

---

src/app/freelancer/market/page.tsx
src/components/shared/JobCard.tsx

fixed the project apply problem and ui card

---

src/components/freelancer/project/bidsDetail.tsx

* update bidsDetail card and homeTableComponent card
* resolve all the changes requested by Divesh-singh
* fix: lint and prettier errors
* fix
* fix (#494)
---------

Divyank aug 16 (#496)

---

src/app/business/Projects/page.tsx
src/components/dialogs/addProject.tsx
src/components/form/resumeform/WorkExperienceInfo.tsx
src/components/shared/ProfileSidebar.tsx
src/components/shared/StoryAccordionItem.tsx
src/components/shared/TaskDropdown.tsx
src/components/shared/TaskUpdateDetailDialog.tsx

Removed some unnecessary logs.

---

src/components/custom-table/CustomTable.tsx

Fixed error in Bids

---

src/app/freelancer/settings/resume/page.tsx
src/components/resumeEditor/editor.tsx

[Uploading Resume-Aaru-G-2025-09-03.pdf…]()

DH-10. Added a soft delete functionality and also improved the styling.

---

src/app/business/project/[project_id]/page.tsx
src/components/business/projectSkillCard.tsx

Added teams for various profiles when one sees profiles in projects at the business end.

Added teams in business Project

---

src/app/business/project/[project_id]/milestone/page.tsx
src/app/project/[project_id]/milestone/page.tsx
src/components/freelancer/FreelancerList.tsx
src/components/shared/CreateProjectGroupDialog.tsx
src/components/shared/CreateProjectTeamGroupDialog.tsx
src/components/shared/MilestoneCards.tsx
src/components/shared/MilestoneTimeline.tsx
src/components/shared/StoriesAccodian.tsx
src/components/shared/StoriesSection.tsx
src/components/shared/StoryAccordionItem.tsx
src/utils/common/firestoreUtils.tsx

Added the freelancer or goup chat functionality and made the ui responsive.

---

src/app/freelancer/settings/profiles/[profileId]/page.tsx

Fixed the problem of the now showing the skills and domains in the freelancer profiles.

[DH-63]-FEAT-Skiils-Doamins-Fix

---

src/components/shared/chat.tsx
src/components/shared/reactions.tsx

I have changed the Reaction to the comment. The emoji takes the full line of space into the position at left bottom site

[DH 11] freelance react element
